name: Pull Request

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.editorconfig'

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Linting
        run: yarn lint

      - name: Type Check
        run: yarn type-check

      - name: Unit Testing
        run: yarn test:coverage

  publish:
    name: Publish (dry-run)
    runs-on: ubuntu-latest
    needs: validate
    if: ${{ !contains(github.head_ref, 'renovate/') }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - id: publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: true
          check-version: true

      - if: steps.publish.outputs.type != 'none' || steps.publish.outputs.version >= steps.publish.outputs.old-version
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
